# Generated by Django 3.1 on 2020-12-03 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201203_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=50, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(verbose_name='Коротке резюме'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Посада'),
        ),
    ]
