# Generated by Django 3.1 on 2020-12-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201203_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='anons',
            new_name='city',
        ),
    ]
