# Generated by Django 3.1 on 2020-12-03 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20201203_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
